dist: trusty
language: scala
scala: 2.12.6
env:
- JDK=oraclejdk8
jdk:
- oraclejdk8

script:
 - sbt -jvm-opts travis/jvmopts.compile test:compile
 # - sbt -jvm-opts travis/jvmopts.test test
 # - sbt -jvm-opts travis/jvmopts.test scalastyle
 # - sbt -jvm-opts travis/jvmopts.assembly assembly
 # - sbt clean coverage test coverageReport

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.m2/repository

