dist: trusty
language: scala
jdk: oraclejdk8

scala:
   - 2.12.6

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt


jobs:
  include:
    - stage: compile
      script: sbt compile
    #- stage: test
    #  script: sbt test
      
stages:
  - compile
  - test
