// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package com.upblockchain.lightcone.proto;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoDemoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.upblockchain.lightcone.proto.ProtoDemo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string query = 1;</code>
     */
    java.lang.String getQuery();
    /**
     * <code>optional string query = 1;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <code>optional int64 demoId = 2;</code>
     */
    long getDemoId();
  }
  /**
   * Protobuf type {@code com.upblockchain.lightcone.proto.ProtoDemo}
   */
  public  static final class ProtoDemo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.upblockchain.lightcone.proto.ProtoDemo)
      ProtoDemoOrBuilder {
    // Use ProtoDemo.newBuilder() to construct.
    private ProtoDemo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoDemo() {
      query_ = "";
      demoId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProtoDemo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              query_ = s;
              break;
            }
            case 16: {

              demoId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_ProtoDemo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_ProtoDemo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.upblockchain.lightcone.proto.Data.ProtoDemo.class, com.upblockchain.lightcone.proto.Data.ProtoDemo.Builder.class);
    }

    public static final int QUERY_FIELD_NUMBER = 1;
    private volatile java.lang.Object query_;
    /**
     * <code>optional string query = 1;</code>
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      }
    }
    /**
     * <code>optional string query = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEMOID_FIELD_NUMBER = 2;
    private long demoId_;
    /**
     * <code>optional int64 demoId = 2;</code>
     */
    public long getDemoId() {
      return demoId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getQueryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
      }
      if (demoId_ != 0L) {
        output.writeInt64(2, demoId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getQueryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
      }
      if (demoId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, demoId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.upblockchain.lightcone.proto.Data.ProtoDemo)) {
        return super.equals(obj);
      }
      com.upblockchain.lightcone.proto.Data.ProtoDemo other = (com.upblockchain.lightcone.proto.Data.ProtoDemo) obj;

      boolean result = true;
      result = result && getQuery()
          .equals(other.getQuery());
      result = result && (getDemoId()
          == other.getDemoId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery().hashCode();
      hash = (37 * hash) + DEMOID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDemoId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.upblockchain.lightcone.proto.Data.ProtoDemo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.upblockchain.lightcone.proto.Data.ProtoDemo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.ProtoDemo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.upblockchain.lightcone.proto.Data.ProtoDemo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.ProtoDemo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.upblockchain.lightcone.proto.Data.ProtoDemo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.ProtoDemo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.upblockchain.lightcone.proto.Data.ProtoDemo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.ProtoDemo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.upblockchain.lightcone.proto.Data.ProtoDemo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.upblockchain.lightcone.proto.Data.ProtoDemo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.upblockchain.lightcone.proto.ProtoDemo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.upblockchain.lightcone.proto.ProtoDemo)
        com.upblockchain.lightcone.proto.Data.ProtoDemoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_ProtoDemo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_ProtoDemo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.upblockchain.lightcone.proto.Data.ProtoDemo.class, com.upblockchain.lightcone.proto.Data.ProtoDemo.Builder.class);
      }

      // Construct using com.upblockchain.lightcone.proto.Data.ProtoDemo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        query_ = "";

        demoId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_ProtoDemo_descriptor;
      }

      public com.upblockchain.lightcone.proto.Data.ProtoDemo getDefaultInstanceForType() {
        return com.upblockchain.lightcone.proto.Data.ProtoDemo.getDefaultInstance();
      }

      public com.upblockchain.lightcone.proto.Data.ProtoDemo build() {
        com.upblockchain.lightcone.proto.Data.ProtoDemo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.upblockchain.lightcone.proto.Data.ProtoDemo buildPartial() {
        com.upblockchain.lightcone.proto.Data.ProtoDemo result = new com.upblockchain.lightcone.proto.Data.ProtoDemo(this);
        result.query_ = query_;
        result.demoId_ = demoId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.upblockchain.lightcone.proto.Data.ProtoDemo) {
          return mergeFrom((com.upblockchain.lightcone.proto.Data.ProtoDemo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.upblockchain.lightcone.proto.Data.ProtoDemo other) {
        if (other == com.upblockchain.lightcone.proto.Data.ProtoDemo.getDefaultInstance()) return this;
        if (!other.getQuery().isEmpty()) {
          query_ = other.query_;
          onChanged();
        }
        if (other.getDemoId() != 0L) {
          setDemoId(other.getDemoId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.upblockchain.lightcone.proto.Data.ProtoDemo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.upblockchain.lightcone.proto.Data.ProtoDemo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object query_ = "";
      /**
       * <code>optional string query = 1;</code>
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          query_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public Builder clearQuery() {
        
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        query_ = value;
        onChanged();
        return this;
      }

      private long demoId_ ;
      /**
       * <code>optional int64 demoId = 2;</code>
       */
      public long getDemoId() {
        return demoId_;
      }
      /**
       * <code>optional int64 demoId = 2;</code>
       */
      public Builder setDemoId(long value) {
        
        demoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 demoId = 2;</code>
       */
      public Builder clearDemoId() {
        
        demoId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.upblockchain.lightcone.proto.ProtoDemo)
    }

    // @@protoc_insertion_point(class_scope:com.upblockchain.lightcone.proto.ProtoDemo)
    private static final com.upblockchain.lightcone.proto.Data.ProtoDemo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.upblockchain.lightcone.proto.Data.ProtoDemo();
    }

    public static com.upblockchain.lightcone.proto.Data.ProtoDemo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoDemo>
        PARSER = new com.google.protobuf.AbstractParser<ProtoDemo>() {
      public ProtoDemo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtoDemo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoDemo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoDemo> getParserForType() {
      return PARSER;
    }

    public com.upblockchain.lightcone.proto.Data.ProtoDemo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PaginationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.upblockchain.lightcone.proto.Pagination)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 index = 1;</code>
     */
    int getIndex();

    /**
     * <code>optional int32 size = 2;</code>
     */
    int getSize();
  }
  /**
   * Protobuf type {@code com.upblockchain.lightcone.proto.Pagination}
   */
  public  static final class Pagination extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.upblockchain.lightcone.proto.Pagination)
      PaginationOrBuilder {
    // Use Pagination.newBuilder() to construct.
    private Pagination(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pagination() {
      index_ = 0;
      size_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Pagination(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              index_ = input.readInt32();
              break;
            }
            case 16: {

              size_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_Pagination_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_Pagination_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.upblockchain.lightcone.proto.Data.Pagination.class, com.upblockchain.lightcone.proto.Data.Pagination.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>optional int32 index = 1;</code>
     */
    public int getIndex() {
      return index_;
    }

    public static final int SIZE_FIELD_NUMBER = 2;
    private int size_;
    /**
     * <code>optional int32 size = 2;</code>
     */
    public int getSize() {
      return size_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeInt32(1, index_);
      }
      if (size_ != 0) {
        output.writeInt32(2, size_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, index_);
      }
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, size_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.upblockchain.lightcone.proto.Data.Pagination)) {
        return super.equals(obj);
      }
      com.upblockchain.lightcone.proto.Data.Pagination other = (com.upblockchain.lightcone.proto.Data.Pagination) obj;

      boolean result = true;
      result = result && (getIndex()
          == other.getIndex());
      result = result && (getSize()
          == other.getSize());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.upblockchain.lightcone.proto.Data.Pagination parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.upblockchain.lightcone.proto.Data.Pagination parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.Pagination parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.upblockchain.lightcone.proto.Data.Pagination parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.Pagination parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.upblockchain.lightcone.proto.Data.Pagination parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.Pagination parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.upblockchain.lightcone.proto.Data.Pagination parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.Pagination parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.upblockchain.lightcone.proto.Data.Pagination parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.upblockchain.lightcone.proto.Data.Pagination prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.upblockchain.lightcone.proto.Pagination}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.upblockchain.lightcone.proto.Pagination)
        com.upblockchain.lightcone.proto.Data.PaginationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_Pagination_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_Pagination_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.upblockchain.lightcone.proto.Data.Pagination.class, com.upblockchain.lightcone.proto.Data.Pagination.Builder.class);
      }

      // Construct using com.upblockchain.lightcone.proto.Data.Pagination.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        index_ = 0;

        size_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_Pagination_descriptor;
      }

      public com.upblockchain.lightcone.proto.Data.Pagination getDefaultInstanceForType() {
        return com.upblockchain.lightcone.proto.Data.Pagination.getDefaultInstance();
      }

      public com.upblockchain.lightcone.proto.Data.Pagination build() {
        com.upblockchain.lightcone.proto.Data.Pagination result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.upblockchain.lightcone.proto.Data.Pagination buildPartial() {
        com.upblockchain.lightcone.proto.Data.Pagination result = new com.upblockchain.lightcone.proto.Data.Pagination(this);
        result.index_ = index_;
        result.size_ = size_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.upblockchain.lightcone.proto.Data.Pagination) {
          return mergeFrom((com.upblockchain.lightcone.proto.Data.Pagination)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.upblockchain.lightcone.proto.Data.Pagination other) {
        if (other == com.upblockchain.lightcone.proto.Data.Pagination.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.upblockchain.lightcone.proto.Data.Pagination parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.upblockchain.lightcone.proto.Data.Pagination) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int index_ ;
      /**
       * <code>optional int32 index = 1;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <code>optional int32 index = 1;</code>
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 index = 1;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>optional int32 size = 2;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>optional int32 size = 2;</code>
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 size = 2;</code>
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.upblockchain.lightcone.proto.Pagination)
    }

    // @@protoc_insertion_point(class_scope:com.upblockchain.lightcone.proto.Pagination)
    private static final com.upblockchain.lightcone.proto.Data.Pagination DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.upblockchain.lightcone.proto.Data.Pagination();
    }

    public static com.upblockchain.lightcone.proto.Data.Pagination getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pagination>
        PARSER = new com.google.protobuf.AbstractParser<Pagination>() {
      public Pagination parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Pagination(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pagination> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pagination> getParserForType() {
      return PARSER;
    }

    public com.upblockchain.lightcone.proto.Data.Pagination getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrderQueryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.upblockchain.lightcone.proto.OrderQuery)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string orderHash = 1;</code>
     */
    java.lang.String getOrderHash();
    /**
     * <code>optional string orderHash = 1;</code>
     */
    com.google.protobuf.ByteString
        getOrderHashBytes();

    /**
     * <code>optional string owner = 2;</code>
     */
    java.lang.String getOwner();
    /**
     * <code>optional string owner = 2;</code>
     */
    com.google.protobuf.ByteString
        getOwnerBytes();
  }
  /**
   * Protobuf type {@code com.upblockchain.lightcone.proto.OrderQuery}
   */
  public  static final class OrderQuery extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.upblockchain.lightcone.proto.OrderQuery)
      OrderQueryOrBuilder {
    // Use OrderQuery.newBuilder() to construct.
    private OrderQuery(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderQuery() {
      orderHash_ = "";
      owner_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OrderQuery(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              orderHash_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              owner_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_OrderQuery_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_OrderQuery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.upblockchain.lightcone.proto.Data.OrderQuery.class, com.upblockchain.lightcone.proto.Data.OrderQuery.Builder.class);
    }

    public static final int ORDERHASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object orderHash_;
    /**
     * <code>optional string orderHash = 1;</code>
     */
    public java.lang.String getOrderHash() {
      java.lang.Object ref = orderHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderHash_ = s;
        return s;
      }
    }
    /**
     * <code>optional string orderHash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrderHashBytes() {
      java.lang.Object ref = orderHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OWNER_FIELD_NUMBER = 2;
    private volatile java.lang.Object owner_;
    /**
     * <code>optional string owner = 2;</code>
     */
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      }
    }
    /**
     * <code>optional string owner = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOrderHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderHash_);
      }
      if (!getOwnerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, owner_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOrderHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderHash_);
      }
      if (!getOwnerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, owner_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.upblockchain.lightcone.proto.Data.OrderQuery)) {
        return super.equals(obj);
      }
      com.upblockchain.lightcone.proto.Data.OrderQuery other = (com.upblockchain.lightcone.proto.Data.OrderQuery) obj;

      boolean result = true;
      result = result && getOrderHash()
          .equals(other.getOrderHash());
      result = result && getOwner()
          .equals(other.getOwner());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ORDERHASH_FIELD_NUMBER;
      hash = (53 * hash) + getOrderHash().hashCode();
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.upblockchain.lightcone.proto.Data.OrderQuery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderQuery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderQuery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderQuery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderQuery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderQuery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderQuery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderQuery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderQuery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderQuery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.upblockchain.lightcone.proto.Data.OrderQuery prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.upblockchain.lightcone.proto.OrderQuery}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.upblockchain.lightcone.proto.OrderQuery)
        com.upblockchain.lightcone.proto.Data.OrderQueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_OrderQuery_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_OrderQuery_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.upblockchain.lightcone.proto.Data.OrderQuery.class, com.upblockchain.lightcone.proto.Data.OrderQuery.Builder.class);
      }

      // Construct using com.upblockchain.lightcone.proto.Data.OrderQuery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        orderHash_ = "";

        owner_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_OrderQuery_descriptor;
      }

      public com.upblockchain.lightcone.proto.Data.OrderQuery getDefaultInstanceForType() {
        return com.upblockchain.lightcone.proto.Data.OrderQuery.getDefaultInstance();
      }

      public com.upblockchain.lightcone.proto.Data.OrderQuery build() {
        com.upblockchain.lightcone.proto.Data.OrderQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.upblockchain.lightcone.proto.Data.OrderQuery buildPartial() {
        com.upblockchain.lightcone.proto.Data.OrderQuery result = new com.upblockchain.lightcone.proto.Data.OrderQuery(this);
        result.orderHash_ = orderHash_;
        result.owner_ = owner_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.upblockchain.lightcone.proto.Data.OrderQuery) {
          return mergeFrom((com.upblockchain.lightcone.proto.Data.OrderQuery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.upblockchain.lightcone.proto.Data.OrderQuery other) {
        if (other == com.upblockchain.lightcone.proto.Data.OrderQuery.getDefaultInstance()) return this;
        if (!other.getOrderHash().isEmpty()) {
          orderHash_ = other.orderHash_;
          onChanged();
        }
        if (!other.getOwner().isEmpty()) {
          owner_ = other.owner_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.upblockchain.lightcone.proto.Data.OrderQuery parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.upblockchain.lightcone.proto.Data.OrderQuery) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object orderHash_ = "";
      /**
       * <code>optional string orderHash = 1;</code>
       */
      public java.lang.String getOrderHash() {
        java.lang.Object ref = orderHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string orderHash = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOrderHashBytes() {
        java.lang.Object ref = orderHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string orderHash = 1;</code>
       */
      public Builder setOrderHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderHash = 1;</code>
       */
      public Builder clearOrderHash() {
        
        orderHash_ = getDefaultInstance().getOrderHash();
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderHash = 1;</code>
       */
      public Builder setOrderHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderHash_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>optional string owner = 2;</code>
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string owner = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string owner = 2;</code>
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string owner = 2;</code>
       */
      public Builder clearOwner() {
        
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>optional string owner = 2;</code>
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        owner_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.upblockchain.lightcone.proto.OrderQuery)
    }

    // @@protoc_insertion_point(class_scope:com.upblockchain.lightcone.proto.OrderQuery)
    private static final com.upblockchain.lightcone.proto.Data.OrderQuery DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.upblockchain.lightcone.proto.Data.OrderQuery();
    }

    public static com.upblockchain.lightcone.proto.Data.OrderQuery getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderQuery>
        PARSER = new com.google.protobuf.AbstractParser<OrderQuery>() {
      public OrderQuery parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OrderQuery(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderQuery> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderQuery> getParserForType() {
      return PARSER;
    }

    public com.upblockchain.lightcone.proto.Data.OrderQuery getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrderResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.upblockchain.lightcone.proto.OrderResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string orderHash = 1;</code>
     */
    java.lang.String getOrderHash();
    /**
     * <code>optional string orderHash = 1;</code>
     */
    com.google.protobuf.ByteString
        getOrderHashBytes();

    /**
     * <code>optional int64 validUntil = 2;</code>
     */
    long getValidUntil();
  }
  /**
   * Protobuf type {@code com.upblockchain.lightcone.proto.OrderResult}
   */
  public  static final class OrderResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.upblockchain.lightcone.proto.OrderResult)
      OrderResultOrBuilder {
    // Use OrderResult.newBuilder() to construct.
    private OrderResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderResult() {
      orderHash_ = "";
      validUntil_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OrderResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              orderHash_ = s;
              break;
            }
            case 16: {

              validUntil_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_OrderResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_OrderResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.upblockchain.lightcone.proto.Data.OrderResult.class, com.upblockchain.lightcone.proto.Data.OrderResult.Builder.class);
    }

    public static final int ORDERHASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object orderHash_;
    /**
     * <code>optional string orderHash = 1;</code>
     */
    public java.lang.String getOrderHash() {
      java.lang.Object ref = orderHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderHash_ = s;
        return s;
      }
    }
    /**
     * <code>optional string orderHash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrderHashBytes() {
      java.lang.Object ref = orderHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALIDUNTIL_FIELD_NUMBER = 2;
    private long validUntil_;
    /**
     * <code>optional int64 validUntil = 2;</code>
     */
    public long getValidUntil() {
      return validUntil_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOrderHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderHash_);
      }
      if (validUntil_ != 0L) {
        output.writeInt64(2, validUntil_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOrderHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderHash_);
      }
      if (validUntil_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, validUntil_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.upblockchain.lightcone.proto.Data.OrderResult)) {
        return super.equals(obj);
      }
      com.upblockchain.lightcone.proto.Data.OrderResult other = (com.upblockchain.lightcone.proto.Data.OrderResult) obj;

      boolean result = true;
      result = result && getOrderHash()
          .equals(other.getOrderHash());
      result = result && (getValidUntil()
          == other.getValidUntil());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ORDERHASH_FIELD_NUMBER;
      hash = (53 * hash) + getOrderHash().hashCode();
      hash = (37 * hash) + VALIDUNTIL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValidUntil());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.upblockchain.lightcone.proto.Data.OrderResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.upblockchain.lightcone.proto.Data.OrderResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.upblockchain.lightcone.proto.Data.OrderResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.upblockchain.lightcone.proto.OrderResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.upblockchain.lightcone.proto.OrderResult)
        com.upblockchain.lightcone.proto.Data.OrderResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_OrderResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_OrderResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.upblockchain.lightcone.proto.Data.OrderResult.class, com.upblockchain.lightcone.proto.Data.OrderResult.Builder.class);
      }

      // Construct using com.upblockchain.lightcone.proto.Data.OrderResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        orderHash_ = "";

        validUntil_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.upblockchain.lightcone.proto.Data.internal_static_com_upblockchain_lightcone_proto_OrderResult_descriptor;
      }

      public com.upblockchain.lightcone.proto.Data.OrderResult getDefaultInstanceForType() {
        return com.upblockchain.lightcone.proto.Data.OrderResult.getDefaultInstance();
      }

      public com.upblockchain.lightcone.proto.Data.OrderResult build() {
        com.upblockchain.lightcone.proto.Data.OrderResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.upblockchain.lightcone.proto.Data.OrderResult buildPartial() {
        com.upblockchain.lightcone.proto.Data.OrderResult result = new com.upblockchain.lightcone.proto.Data.OrderResult(this);
        result.orderHash_ = orderHash_;
        result.validUntil_ = validUntil_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.upblockchain.lightcone.proto.Data.OrderResult) {
          return mergeFrom((com.upblockchain.lightcone.proto.Data.OrderResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.upblockchain.lightcone.proto.Data.OrderResult other) {
        if (other == com.upblockchain.lightcone.proto.Data.OrderResult.getDefaultInstance()) return this;
        if (!other.getOrderHash().isEmpty()) {
          orderHash_ = other.orderHash_;
          onChanged();
        }
        if (other.getValidUntil() != 0L) {
          setValidUntil(other.getValidUntil());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.upblockchain.lightcone.proto.Data.OrderResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.upblockchain.lightcone.proto.Data.OrderResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object orderHash_ = "";
      /**
       * <code>optional string orderHash = 1;</code>
       */
      public java.lang.String getOrderHash() {
        java.lang.Object ref = orderHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string orderHash = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOrderHashBytes() {
        java.lang.Object ref = orderHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string orderHash = 1;</code>
       */
      public Builder setOrderHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderHash = 1;</code>
       */
      public Builder clearOrderHash() {
        
        orderHash_ = getDefaultInstance().getOrderHash();
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderHash = 1;</code>
       */
      public Builder setOrderHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderHash_ = value;
        onChanged();
        return this;
      }

      private long validUntil_ ;
      /**
       * <code>optional int64 validUntil = 2;</code>
       */
      public long getValidUntil() {
        return validUntil_;
      }
      /**
       * <code>optional int64 validUntil = 2;</code>
       */
      public Builder setValidUntil(long value) {
        
        validUntil_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 validUntil = 2;</code>
       */
      public Builder clearValidUntil() {
        
        validUntil_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.upblockchain.lightcone.proto.OrderResult)
    }

    // @@protoc_insertion_point(class_scope:com.upblockchain.lightcone.proto.OrderResult)
    private static final com.upblockchain.lightcone.proto.Data.OrderResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.upblockchain.lightcone.proto.Data.OrderResult();
    }

    public static com.upblockchain.lightcone.proto.Data.OrderResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderResult>
        PARSER = new com.google.protobuf.AbstractParser<OrderResult>() {
      public OrderResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OrderResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderResult> getParserForType() {
      return PARSER;
    }

    public com.upblockchain.lightcone.proto.Data.OrderResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_upblockchain_lightcone_proto_ProtoDemo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_upblockchain_lightcone_proto_ProtoDemo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_upblockchain_lightcone_proto_Pagination_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_upblockchain_lightcone_proto_Pagination_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_upblockchain_lightcone_proto_OrderQuery_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_upblockchain_lightcone_proto_OrderQuery_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_upblockchain_lightcone_proto_OrderResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_upblockchain_lightcone_proto_OrderResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\022 com.upblockchain.lightcone" +
      ".proto\"*\n\tProtoDemo\022\r\n\005query\030\001 \001(\t\022\016\n\006de" +
      "moId\030\002 \001(\003\")\n\nPagination\022\r\n\005index\030\001 \001(\005\022" +
      "\014\n\004size\030\002 \001(\005\".\n\nOrderQuery\022\021\n\torderHash" +
      "\030\001 \001(\t\022\r\n\005owner\030\002 \001(\t\"4\n\013OrderResult\022\021\n\t" +
      "orderHash\030\001 \001(\t\022\022\n\nvalidUntil\030\002 \001(\003b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_upblockchain_lightcone_proto_ProtoDemo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_upblockchain_lightcone_proto_ProtoDemo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_upblockchain_lightcone_proto_ProtoDemo_descriptor,
        new java.lang.String[] { "Query", "DemoId", });
    internal_static_com_upblockchain_lightcone_proto_Pagination_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_upblockchain_lightcone_proto_Pagination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_upblockchain_lightcone_proto_Pagination_descriptor,
        new java.lang.String[] { "Index", "Size", });
    internal_static_com_upblockchain_lightcone_proto_OrderQuery_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_upblockchain_lightcone_proto_OrderQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_upblockchain_lightcone_proto_OrderQuery_descriptor,
        new java.lang.String[] { "OrderHash", "Owner", });
    internal_static_com_upblockchain_lightcone_proto_OrderResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_upblockchain_lightcone_proto_OrderResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_upblockchain_lightcone_proto_OrderResult_descriptor,
        new java.lang.String[] { "OrderHash", "ValidUntil", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
